# src/app.py
from flask import Flask, jsonify
import os, pandas as pd
from anomaly_detector import *
from alert_service import send_alerts

# make sure import paths are correct
import sys
sys.path.append(os.path.dirname(__file__))

from anomaly_detector import *
from alert_service import send_alerts

app = Flask(__name__)

@app.route("/run_check", methods=["POST", "GET"])
def run_check():
    # run detector -> reads daily_metrics.csv and writes anomaly_alerts.csv
    from anomaly_detector import DATAPATH as _ ;  # ensure path used inside module
    import anomaly_detector as ad
    ad  # module executed at import in our design
    # read alerts generated by anomaly_detector.py (if any)
    path = os.path.join(os.path.dirname(__file__), "..", "data", "anomaly_alerts.csv")
    if os.path.exists(path):
        alerts = pd.read_csv(path).to_dict(orient="records")
        send_alerts(alerts)
        return jsonify({"alerts": alerts})
    else:
        return jsonify({"alerts": []})

if __name__ == "__main__":
    app.run(debug=True, port=5100)
